config/routes.rb
Rails.application.routes.draw do
  root "artists#index"

  resources :artists do
  resources :songs

  end

  resources :songs, except: [:new, :create]


  # # get "artists" => "artists#index"
  # get "artist/:id/songs/new" => "songs#new",as: :new_song
  # # get "artists/:id" => "artists#show"
  # get "songs" => "artists#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_many :photos, dependent: :destroy

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist
  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    redirect_to root_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show]

  def index
    @songs = Song.all
  end

  def show
    @song.artist = @artist.song
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.build
 end

  def create
    @artist = Artist.find(params[:artist_id])

    @song = @artist.songs.build(song_params)


    if @song.save
      redirect_to artist_path(@artist), notice: "Song created"
    else
      render :new
    end
  end

  def destroy
    @song = Song.find(params[:id])
    if @song.destroy
    redirect_to @song.artist, notice: "Song deleted"
  end
end

  private

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:name, :artist_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
<h3>Refactory Records</h3>

<h1><% @artists.each do |artist| %><h1>
    <p><%= link_to artist.name, artist_path(artist.id) %></p>
    <img src='<%= artist.image_url %>' />  
    <% end %>

app/views/artists/show.html.erb
<h3>Refactory Records</h3>

<!-- Photos -->
<h1><%= @artist.name %></h1>
<%= image_tag @artist.image_url %>


  <h2>List of songs<h2>
  <% if @artist.songs.any? %>
  <h3><% @artist.songs.each do |song| %></h3>
  <p><%= song.name %></p>
  <%= link_to "Delete This Song", song, method: :delete %>
    <% end %>
  <% else %>
  <p>This Artist has no songs.</p>
    <% end %>

    <hr>

    <%= link_to "Add a New Song", new_artist_song_path(@artist) %>
    <%= link_to "Delete this Artist", artist_path(@artist.id), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= yield %>

  <br><br>
  <hr>

  <h3><%= link_to "All Artists", root_path %><h3>

  </body>
</html>

app/views/songs/new.html.erb
<h3>Refactory Records</h3>
<h1>Add a New Song</h1>

<%= form_for ([:artist, @song]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit "Create" %>
<% end %>